"""Add body_part and sets to Workout model

Revision ID: 35c39524fc37
Revises: 1f7ba23699df
Create Date: 2024-08-13 20:20:08.083425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c39524fc37'
down_revision = '1f7ba23699df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bodyPart', sa.String(length=100), nullable=False))
        batch_op.drop_column('calories_burned')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('calories_burned', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('bodyPart')
        batch_op.drop_column('weight')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')

    # ### end Alembic commands ###
